sap.ui.define([], function () {
	"use strict";
	return {
		_validateInput: function (oInput) {
			var oBinding = oInput.getBinding("value");
			var sValueState = "None";
			var bValidationError = false;

			try {
				oBinding.getType().validateValue(oInput.getValue());
			} catch (oException) {
				sValueState = "Error";
				bValidationError = true;
			}
			if (oInput.getValue() == "" && oInput.mProperties.required == true) {
				sValueState = "Error";
				bValidationError = true;
			}
			oInput.setValueState(sValueState);

			return bValidationError;
		},
		fnDateModel: function (elm) {
			var oDateModel = new sap.ui.model.json.JSONModel();
			oDateModel.setData({
				dateValueDRS2: new Date(2018, 1, 1),
				secondDateValueDRS2: new Date(),
				dateCurrent: new Date(),
				enableVin : true,
				editPlan : true,
				editAgrType : true
			});
			return elm.getView().setModel(oDateModel, "DateModel");
		},
			getTypeOfAggreementKey: function (planTypeStr, self) {
			var oBundle = self.getView().getModel("i18n").getResourceBundle();
			if (planTypeStr === oBundle.getText("NEWVEHICLEAGREEMENT")) {
				return "NEW VEHICLE AGREEMENT";
			}
			if (planTypeStr === oBundle.getText("USEDVEHICLEAGREEMENT")) {
				return "USED VEHICLE AGREEMENT";
			}
			if (planTypeStr === oBundle.getText("EXTENSION")) {
				return "EXTENSION";
			}

		},
		_fnObject: function (elm, stat, prnt) {
			var currentDate = new Date();

			var crudObj = {
				DBOperation: elm,
				BPTYPE: prnt.getView().getModel("LocalDataModel").getProperty("/PricingModelData/BPTYPE"),
				ZecpIntApp: "",
				ZecpMake: prnt.oECPData.ZecpMake,
				ZecpAppNum: "",
				ZecpVin: prnt.oECPData.ZecpVin.trim(),
				ZecpAgrNum: "",
				ZecpDealcode: prnt.getModel("LocalDataModel").getProperty("/sCurrentDealer"),
				ZecpAppStat: stat,
				ZecpSaleDate: prnt._fnDateFormat(prnt.oECPData.ZecpSaleDate),
				ZecpOdometer: prnt.oECPData.ZecpOdometer,
				ZecpAgrType: this.getTypeOfAggreementKey(prnt.oECPData.ZecpAgrType, prnt),
				ZecpEffDate: null,
				ZecpExpDate: null,
				ZecpDealName: "",
				ZecpSurchrgFl: "N",
				ZecpPreowned: prnt.oECPData.PrOwndCert,
				ZecpCustNum: prnt.oECPData.ZecpCustNum,
				ZecpCustName: prnt.oECPData.ZecpCustName,
				ZecpMidName: "",
				ZecpLastName: prnt.oECPData.ZecpLastName,
				ZecpBusPhone: prnt.oECPData.ZecpBusPhone,
				ZecpEmail: prnt.oECPData.ZecpEmail,
				ZecpSubDate: prnt._fnDateFormat(currentDate),
				ZecpAutocode: prnt.oECPData.ZecpAutocode,
				ZecpVehPrice: prnt.oECPData.ZecpVehPrice || "0.00",
				ZecpAmtFin: prnt.oECPData.ZecpAmtFin || "0.00",
				ZecpLienholder: prnt.oECPData.ZecpLienholder || "",
				ZecpLienterms: prnt.oECPData.ZecpLienterms || "00",
				ZecpPlancode: prnt.oECPData.ZecpPlancode || "",
				ZecpRetPrice: prnt.oECPData.ZecpRetPrice || "0.00",
				ZecpDefSurchrg: prnt.oECPData.ZecpDefSurchrg || "0.00",
				ZecpVehSurchrgAmt: prnt.oECPData.ZecpVehSurchrgAmt || "0.00",
				ZecpListpurprice: prnt.oECPData.ZecpListpurprice || "0.00",
				ZecpVehsurchrg: prnt.oECPData.ZecpVehSurchrgAmt || "0.00",
				ZecpRoadhazard: prnt.oECPData.ZecpRoadhazard,
				ZecpBenefitsFlg: prnt.getView().getModel("EcpFieldData").getProperty("/ZecpBenefitsFlg"),
				BccAgrmntSaleDt: prnt._fnDateFormat(prnt.oECPData.ZecpSaleDate),
				ZecpSource: "ECP",
				ZecpDatecreated: prnt._fnDateFormat(currentDate),
				ZecpLastupdate: null,
				ZecpSaletype: "",
				ZecpFueltype: "G",
				ZecpCylnum: "4",
				ZecpAdddata1: "",
				ZecpAdddata2: "",
				ZecpAdddata3: "",
				ZecpAdddata4: "",
				ZecpAdddata5: "",
				ZecpCompName: "",
				ZecpAddress: prnt.oECPData.ZecpAddress,
				ZecpCity: prnt.oECPData.ZecpCity,
				ZecpProvince: prnt.oECPData.ZecpProvince,
				ZecpPostalcode: prnt.oECPData.ZecpPostalcode,
				ZecpHomePhone: prnt.oECPData.ZecpHomePhone,
				ZecpBusExt: "",
				ZecpBusOrInd: "",
				ZecpModelcode: prnt.oECPData.ZecpModelcode,
				BccEcpAgrmntNum: "",
				BccVin: prnt.oECPData.ZecpVin,
				BccPlanCd: prnt.oECPData.ZecpPlancode,
				BccAplDlrshpNum: prnt.getModel("LocalDataModel").getProperty("/sCurrentDealer"),
				BccAgrStCd: "A",
				AgrStDt: prnt._fnDateFormat(currentDate),
				BccAgrEvTypCd: "NEW",
				BccVoasPartNum: "",
				BccAgrmntDlrNum: prnt.getModel("LocalDataModel").getProperty("/sCurrentDealer"),
				BccEcpAutoCd: prnt.oECPData.ZecpAutocode,
				BccAgrmntExtcntr: "0.00",
				BccAgrmntPrcAmt: prnt.oECPData.ZecpPlanpurchprice || "0.00",
				Dedctble: "",
				VehSurchLst: "",
				BccDtSrchrgFlg: "",
				BccDefSrchrgAmt: prnt.oECPData.ZecpDefSurchrg || "0.00",
				BccAgrmntYrCd: "",
				BccAgrmntSerNo: "0.00",
				BccVehSrchrgFlg: "",
				BccVehSrchrgAmt: prnt.oECPData.ZecpVehSurchrgAmt || "0.00",
				BccDlrCommsnAmt: "0.00",
				BccCdbCustNum: prnt.oECPData.ZecpCustNum,
				BccAgrmntThruKm: "0.00",
				BccLubBnftFlg: "",
				BccVehStsKm: prnt.oECPData.ZecpOdometer,
				BccAgrmntDlrPfl: "",
				BccPlnLienHldr: "",
				BccPlnLienTrmth: "0.00",
				BccPlnLienAmt: "0.00",
				BccDlrNetDebamt: "0.00",
				BccNetDebAmt: "0.00",
				BccNetGwDebAmt: "0.00",
				BccNetGwCreAmt: "0.00",
				BccNetGwOffCre: "0.00",
				BccNetRecvryDeb: "0.00",
				BccCncTsfFee: "0.00",
				BccCustRfndAmt: "0.00",
				BccAdjstdAdmAmt: "0.00",
				BccAdjstdFdAmt: "0.00",
				BccAdjstdRapAmt: "0.00",
				BccAdjstdSurAmt: "0.00",
				BccAgrActSrDes: "",
				BccAdjstrCmnts: "",
				BccUsrCalAmtflg: "",
				BccRdHzrd: "",
				Odmtr: prnt.oECPData.ZecpOdometer,
				TrnfrOdometer: "",
				TrnfrFee: "",
				PrOwndCert: prnt.oECPData.PrOwndCert,
				PrVendorFlag: "",
				BccInscTrnmtFl: "",
				BccRdsdTrnmtFl: "A",
				BccMktngTrnmtFl: "",
				BccDlrDebGst: "0.00",
				BccDlrDebPst: "0.00",
				BccCustRfndGst: "0.00",
				BccCustRfndPst: "0.00",
				BccFinclAjstrId: "",
				BccDebitRequest: "",
				BccCreditRequest: "",
				BccCrtrUserid: "",
				BccCrtnTmstmp: "",
				BccLstUpdPltf: "",
				BccLstUpdPgmid: "",
				BccLstUpdUserid: "",
				BccLstUpdTmstmp: "",
				ZamtFincd: "0.00",
				ZretailPrice: "0.00",
				ZecpPlanpurchprice: prnt.oECPData.ZecpPlanpurchprice || "0.00"
			};
			return crudObj;
		},
		
		funECPBlankObj : function(elm){
				elm.EcpFieldData = new sap.ui.model.json.JSONModel({
					DBOperation: "",
					BPTYPE: "",
					ZecpIntApp: "",
					ZecpMake: "",
					ZecpAppNum: "",
					ZecpVin: "",
					ZecpAgrNum: "",
					ZecpDealcode: "",
					ZecpAppStat: "",
					ZecpSaleDate: "",
					ZecpOdometer: "",
					ZecpAgrType: "",
					ZecpEffDate: "",
					ZecpExpDate: "",
					ZecpDealName: "",
					ZecpSurchrgFl: "",
					ZecpPreowned: "",
					ZecpCustNum: "",
					ZecpCustName: "",
					ZecpMidName: "",
					ZecpLastName: "",
					ZecpBusPhone: "",
					ZecpEmail: "",
					ZecpSubDate: "",
					ZecpAutocode: "",
					ZecpVehPrice: "",
					ZecpAmtFin: "",
					ZecpLienholder: "",
					ZecpLienterms: "",
					ZecpPlancode: "",
					ZecpRetPrice: "",
					ZecpDefSurchrg: "",
					ZecpVehSurchrgAmt: "",
					ZecpListpurprice: "",
					ZecpVehsurchrg: "",
					ZecpRoadhazard: "",
					ZecpBenefitsFlg: "",
					BccAgrmntSaleDt: "",
					ZecpSource: "",
					ZecpDatecreated: "",
					ZecpLastupdate: "",
					ZecpSaletype: "",
					ZecpFueltype: "",
					ZecpCylnum: "",
					ZecpAdddata1: "",
					ZecpAdddata2: "",
					ZecpAdddata3: "",
					ZecpAdddata4: "",
					ZecpAdddata5: "",
					ZecpCompName: "",
					ZecpAddress: "",
					ZecpCity: "",
					ZecpProvince: "",
					ZecpPostalcode: "",
					ZecpHomePhone: "",
					ZecpBusExt: "",
					ZecpBusOrInd: "",
					ZecpModelcode: "",
					BccEcpAgrmntNum: "",
					BccVin: "",
					BccPlanCd: "",
					BccAplDlrshpNum: "",
					BccAgrStCd: "",
					AgrStDt: "",
					BccAgrEvTypCd: "",
					BccVoasPartNum: "",
					BccAgrmntDlrNum: "",
					BccEcpAutoCd: "",
					BccAgrmntExtcntr: "",
					BccAgrmntPrcAmt: "",
					Dedctble: "",
					VehSurchLst: "",
					BccDtSrchrgFlg: "",
					BccDefSrchrgAmt: "",
					BccAgrmntYrCd: "",
					BccAgrmntSerNo: "",
					BccVehSrchrgFlg: "",
					BccVehSrchrgAmt: " ",
					BccDlrCommsnAmt: " ",
					BccCdbCustNum: "",
					BccAgrmntThruKm: " ",
					BccLubBnftFlg: "",
					BccVehStsKm: " ",
					BccAgrmntDlrPfl: "",
					BccPlnLienHldr: "",
					BccPlnLienTrmth: " ",
					BccPlnLienAmt: " ",
					BccDlrNetDebamt: " ",
					BccNetDebAmt: " ",
					BccNetGwDebAmt: " ",
					BccNetGwCreAmt: " ",
					BccNetGwOffCre: " ",
					BccNetRecvryDeb: " ",
					BccCncTsfFee: " ",
					BccCustRfndAmt: " ",
					BccAdjstdAdmAmt: " ",
					BccAdjstdFdAmt: " ",
					BccAdjstdRapAmt: " ",
					BccAdjstdSurAmt: " ",
					BccAgrActSrDes: "",
					BccAdjstrCmnts: "",
					BccUsrCalAmtflg: "",
					BccRdHzrd: "",
					RdHzrdExpDt: "",
					Odmtr: "",
					TrnfrOdometer: "",
					TrnfrDate: "",
					TrnfrFee: "",
					PrOwndCert: "",
					PrVendorFlag: "",
					BccInscTrnmtFl: "",
					BccRdsdTrnmtFl: "",
					BccMktngTrnmtFl: "",
					BccDlrDebGst: " ",
					BccDlrDebPst: " ",
					BccCustRfndGst: " ",
					BccCustRfndPst: " ",
					BccFinclAjstrId: "",
					BccDebitRequest: "",
					BccCreditRequest: "",
					BccCrtrUserid: "",
					BccCrtnTmstmp: "",
					BccLstUpdPltf: "",
					BccLstUpdPgmid: "",
					BccLstUpdUserid: "",
					BccLstUpdTmstmp: "",
					ZamtFincd: " ",
					ZretailPrice: "",
					ZecpRoadhazard1: "",
					ZbenefitFlag1: "", //Added new entity for translation
					ZecpPlanpurchprice: ""

				});
				elm.EcpFieldData.setDefaultBindingMode("TwoWay");
				elm.getView().setModel(elm.EcpFieldData, "EcpFieldData");
		}
	};

});